### ISSUE TITLE
Spotify can't get token ?

### ISSUE THREAD

**Issue by B-Hartley** [YIO-Remote/integration.spotify#15]
Spotify: 0.4.2
remote: 0.4.7

YIO-remote-software-v0.4.7-12-g5813bbaf-20200531_155953-RPi0-release
YIO-integration.spotify-v0.4.2-RPi0-release
YIO-integration.home-assistant-v0.4.7-10-g2da234e-20200530_101638-RPi0-release

have removed Spotify entity and integration and re-added it.

Successfully added, but in the log it says......

> DEBUG api Sent response to client QWebSocket(0x17e99d8) 
> WARN  spotify "Error transferring https://accounts.spotify.com/api/token - server replied: Bad Request" 
> WARN  default QObject::startTimer: Timers cannot have negative intervals

**Comment by martonborzak** [comment]
Could you please describe describe the issue in a bit more detail? Please use the issue template:



## Description


## How to Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behavior


## Screenshots


## Your Environment

* Version used: 
* Running on: 
  - YIO Remote
  - Desktop
  - Standalone Raspberry Pi
* Operating System and version if not running on YIO Remote: 

## Additional context

**Comment by B-Hartley** [comment]
How to Reproduce
Steps to reproduce the behavior:

Remove spotify entity and integration.
Re-install spotify integtation, supply API keys.
Complete installation.
Add entity
add to favourites page.

restart remote from ssh.
read log....


Your Environment
Versions as given above.
Running on YIO remote

**Comment by martonborzak** [comment]
Does the integration work or you just see error messages in the log?

**Comment by B-Hartley** [comment]
no, doesn't work

**Comment by B-Hartley** [comment]
actually, I take that back.  it shows the track that is playing, but the pause button etc. don't work.

**Comment by martonborzak** [comment]
Could you tail the log and see if there's any error message when you press pause?
`tail -f logfile`

**Comment by B-Hartley** [comment]
It says:
WARN  spotify ERROR WITH PUT REQUEST  403 "{\n  \"error\" : {\n    \"status\" : 403,\n    \"message\" : \"Restricted device\"\n  }\n}" 


Is that something in the API settings that I should have set ?

**Comment by martonborzak** [comment]
Looks like you didn't give permission to control devices or your account is restricted for some reason. Do you have a premium account? These features only work with that.

**Comment by B-Hartley** [comment]
Yes, premium.  Let me make sure I used the right spotify account and that i don't have 2 or something

**Comment by B-Hartley** [comment]
it's a premium famliy account

**Comment by martonborzak** [comment]
That should work. When setting up the your API keys, did you allow control of your devices?

**Comment by martonborzak** [comment]
After reading on this `Restricted device` thing, I found that there could be some devices that show up and display info, but they are restricted and cannot be controlled. Seems like you have a device like that. However, I should add this to the integration, that it filters out these restricted devices.

**Comment by B-Hartley** [comment]
I never seemed to have any questions about what I was allowing with the API, where are those options ?  I'm playing Spotify on a SONOS btw.  and I can control it with other things, so I would expect to be able to control it ?

**Comment by martonborzak** [comment]
I don't have Sonos speakers, but I've removed and re-added the integration and it works fine here. I'd suggest to remove the integration. Go to your Spotify Developer Dashboard. Reset the client secret. Then reboot the remote just to be sure. Add the integration again.

**Comment by martonborzak** [comment]
I don't know how but managed to reproduce the issue :) I'm on it!

**Comment by martonborzak** [comment]
Go to your spotify account page, choose Apps in the left sidebar
remove access to the YIO app
then update remote software to v0.4.8
spotify integration to v0.4.3
and webconfig to v0.1.9
after this you should be able to add it and it should work
