### ISSUE TITLE
Add support for Spotify Connect speakers

### ISSUE THREAD

**Issue by martonborzak** [YIO-Remote/integration.spotify#4]
## Expected Behavior or Design
Support for Spotify Connect speakers.

## Possible Solution
Implement a list of speakers on a separate page, like search and playlists now.

## Detailed Description and Additional Information
Spotify API calls needs to be implemented and UI designed.

**Comment by Kclemen** [comment]
Speakers not showing up. Only a blank green screen.

**Comment by martonborzak** [comment]
This feature is not yet implemented, hence the open github issue.
